[package]
name = "rust-http-quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.200", features = ["derive"] }
bincode = { version = "1.3.3" }
serde_json = { version = "1.0" }
chrono = "0.4"